version: '3'
services:
  backend:
    build:
      context: .  # Path to the current Dockerfile
    container_name: backend-dev
    ports:
      - "8888:8888"  # Jupyter exposed port for development
      - "5174:5174"  # Flask or other service port
    volumes:
      - ./src:/app  # Mount the local code for development
    environment:
      - FLASK_ENV=development  # Set environment variables for dev mode
    command: flask run --host=0.0.0.0 --port=5174  # Dev command to run Flask
    tty: true  # Keep the container running

  backend_prod:
    build:
      context: .
    container_name: backend-prod
    ports:
      - "5174:5174"  # Expose the Flask port in production
    environment:
      - FLASK_ENV=production  # Set environment variables for production
    command: flask run --host=0.0.0.0 --port=5174  # Prod command to run Flask
